server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#国际化
  messages:
    basename: i18n/messages
    encoding: UTF-8
#redis
  redis:
    host: 127.0.0.1
    port: 6379
#数据库索引（0到16）
    database: 1

mybatis-plus:
  mapper-locations: classpath:gitspringboot.modules.mapper*

