// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.config.Grpc.message;

/**
 * <pre>
 * 模版新增请求
 * </pre>
 *
 * Protobuf type {@code message.AddTemplateReq}
 */
public  final class AddTemplateReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:message.AddTemplateReq)
    AddTemplateReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddTemplateReq.newBuilder() to construct.
  private AddTemplateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddTemplateReq() {
    templateType_ = 0;
    templateName_ = "";
    templateContent_ = "";
    remark_ = "";
    signName_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddTemplateReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            templateType_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            templateName_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            templateContent_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            remark_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            signName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageProto.internal_static_message_AddTemplateReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageProto.internal_static_message_AddTemplateReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddTemplateReq.class, Builder.class);
  }

  public static final int TEMPLATETYPE_FIELD_NUMBER = 1;
  private int templateType_;
  /**
   * <pre>
   * 模版类型
   * </pre>
   *
   * <code>.message.TemplateType templateType = 1;</code>
   */
  public int getTemplateTypeValue() {
    return templateType_;
  }
  /**
   * <pre>
   * 模版类型
   * </pre>
   *
   * <code>.message.TemplateType templateType = 1;</code>
   */
  public TemplateType getTemplateType() {
    TemplateType result = TemplateType.valueOf(templateType_);
    return result == null ? TemplateType.UNRECOGNIZED : result;
  }

  public static final int TEMPLATENAME_FIELD_NUMBER = 2;
  private volatile Object templateName_;
  /**
   * <pre>
   * 1~30字符
   * </pre>
   *
   * <code>string templateName = 2;</code>
   */
  public String getTemplateName() {
    Object ref = templateName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      templateName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 1~30字符
   * </pre>
   *
   * <code>string templateName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTemplateNameBytes() {
    Object ref = templateName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      templateName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMPLATECONTENT_FIELD_NUMBER = 3;
  private volatile Object templateContent_;
  /**
   * <pre>
   * 1~500字符内
   * </pre>
   *
   * <code>string templateContent = 3;</code>
   */
  public String getTemplateContent() {
    Object ref = templateContent_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      templateContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 1~500字符内
   * </pre>
   *
   * <code>string templateContent = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTemplateContentBytes() {
    Object ref = templateContent_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      templateContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMARK_FIELD_NUMBER = 4;
  private volatile Object remark_;
  /**
   * <pre>
   * 短信模板申请说明
   * </pre>
   *
   * <code>string remark = 4;</code>
   */
  public String getRemark() {
    Object ref = remark_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      remark_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 短信模板申请说明
   * </pre>
   *
   * <code>string remark = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRemarkBytes() {
    Object ref = remark_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      remark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNNAME_FIELD_NUMBER = 5;
  private volatile Object signName_;
  /**
   * <pre>
   * title
   * </pre>
   *
   * <code>string SignName = 5;</code>
   */
  public String getSignName() {
    Object ref = signName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      signName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * title
   * </pre>
   *
   * <code>string SignName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSignNameBytes() {
    Object ref = signName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      signName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (templateType_ != TemplateType.verify_code.getNumber()) {
      output.writeEnum(1, templateType_);
    }
    if (!getTemplateNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, templateName_);
    }
    if (!getTemplateContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, templateContent_);
    }
    if (!getRemarkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, remark_);
    }
    if (!getSignNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, signName_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (templateType_ != TemplateType.verify_code.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, templateType_);
    }
    if (!getTemplateNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, templateName_);
    }
    if (!getTemplateContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, templateContent_);
    }
    if (!getRemarkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, remark_);
    }
    if (!getSignNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, signName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddTemplateReq)) {
      return super.equals(obj);
    }
    AddTemplateReq other = (AddTemplateReq) obj;

    boolean result = true;
    result = result && templateType_ == other.templateType_;
    result = result && getTemplateName()
        .equals(other.getTemplateName());
    result = result && getTemplateContent()
        .equals(other.getTemplateContent());
    result = result && getRemark()
        .equals(other.getRemark());
    result = result && getSignName()
        .equals(other.getSignName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPLATETYPE_FIELD_NUMBER;
    hash = (53 * hash) + templateType_;
    hash = (37 * hash) + TEMPLATENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTemplateName().hashCode();
    hash = (37 * hash) + TEMPLATECONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getTemplateContent().hashCode();
    hash = (37 * hash) + REMARK_FIELD_NUMBER;
    hash = (53 * hash) + getRemark().hashCode();
    hash = (37 * hash) + SIGNNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSignName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddTemplateReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddTemplateReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddTemplateReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddTemplateReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddTemplateReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddTemplateReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddTemplateReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddTemplateReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddTemplateReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AddTemplateReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddTemplateReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddTemplateReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddTemplateReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 模版新增请求
   * </pre>
   *
   * Protobuf type {@code message.AddTemplateReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:message.AddTemplateReq)
      AddTemplateReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_message_AddTemplateReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_message_AddTemplateReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddTemplateReq.class, Builder.class);
    }

    // Construct using gitspringboot.modules.message.AddTemplateReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      templateType_ = 0;

      templateName_ = "";

      templateContent_ = "";

      remark_ = "";

      signName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageProto.internal_static_message_AddTemplateReq_descriptor;
    }

    public AddTemplateReq getDefaultInstanceForType() {
      return AddTemplateReq.getDefaultInstance();
    }

    public AddTemplateReq build() {
      AddTemplateReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AddTemplateReq buildPartial() {
      AddTemplateReq result = new AddTemplateReq(this);
      result.templateType_ = templateType_;
      result.templateName_ = templateName_;
      result.templateContent_ = templateContent_;
      result.remark_ = remark_;
      result.signName_ = signName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddTemplateReq) {
        return mergeFrom((AddTemplateReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddTemplateReq other) {
      if (other == AddTemplateReq.getDefaultInstance()) return this;
      if (other.templateType_ != 0) {
        setTemplateTypeValue(other.getTemplateTypeValue());
      }
      if (!other.getTemplateName().isEmpty()) {
        templateName_ = other.templateName_;
        onChanged();
      }
      if (!other.getTemplateContent().isEmpty()) {
        templateContent_ = other.templateContent_;
        onChanged();
      }
      if (!other.getRemark().isEmpty()) {
        remark_ = other.remark_;
        onChanged();
      }
      if (!other.getSignName().isEmpty()) {
        signName_ = other.signName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddTemplateReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddTemplateReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int templateType_ = 0;
    /**
     * <pre>
     * 模版类型
     * </pre>
     *
     * <code>.message.TemplateType templateType = 1;</code>
     */
    public int getTemplateTypeValue() {
      return templateType_;
    }
    /**
     * <pre>
     * 模版类型
     * </pre>
     *
     * <code>.message.TemplateType templateType = 1;</code>
     */
    public Builder setTemplateTypeValue(int value) {
      templateType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模版类型
     * </pre>
     *
     * <code>.message.TemplateType templateType = 1;</code>
     */
    public TemplateType getTemplateType() {
      TemplateType result = TemplateType.valueOf(templateType_);
      return result == null ? TemplateType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 模版类型
     * </pre>
     *
     * <code>.message.TemplateType templateType = 1;</code>
     */
    public Builder setTemplateType(TemplateType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      templateType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模版类型
     * </pre>
     *
     * <code>.message.TemplateType templateType = 1;</code>
     */
    public Builder clearTemplateType() {
      
      templateType_ = 0;
      onChanged();
      return this;
    }

    private Object templateName_ = "";
    /**
     * <pre>
     * 1~30字符
     * </pre>
     *
     * <code>string templateName = 2;</code>
     */
    public String getTemplateName() {
      Object ref = templateName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        templateName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 1~30字符
     * </pre>
     *
     * <code>string templateName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateNameBytes() {
      Object ref = templateName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        templateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 1~30字符
     * </pre>
     *
     * <code>string templateName = 2;</code>
     */
    public Builder setTemplateName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      templateName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1~30字符
     * </pre>
     *
     * <code>string templateName = 2;</code>
     */
    public Builder clearTemplateName() {
      
      templateName_ = getDefaultInstance().getTemplateName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1~30字符
     * </pre>
     *
     * <code>string templateName = 2;</code>
     */
    public Builder setTemplateNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      templateName_ = value;
      onChanged();
      return this;
    }

    private Object templateContent_ = "";
    /**
     * <pre>
     * 1~500字符内
     * </pre>
     *
     * <code>string templateContent = 3;</code>
     */
    public String getTemplateContent() {
      Object ref = templateContent_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        templateContent_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 1~500字符内
     * </pre>
     *
     * <code>string templateContent = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateContentBytes() {
      Object ref = templateContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        templateContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 1~500字符内
     * </pre>
     *
     * <code>string templateContent = 3;</code>
     */
    public Builder setTemplateContent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      templateContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1~500字符内
     * </pre>
     *
     * <code>string templateContent = 3;</code>
     */
    public Builder clearTemplateContent() {
      
      templateContent_ = getDefaultInstance().getTemplateContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1~500字符内
     * </pre>
     *
     * <code>string templateContent = 3;</code>
     */
    public Builder setTemplateContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      templateContent_ = value;
      onChanged();
      return this;
    }

    private Object remark_ = "";
    /**
     * <pre>
     * 短信模板申请说明
     * </pre>
     *
     * <code>string remark = 4;</code>
     */
    public String getRemark() {
      Object ref = remark_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 短信模板申请说明
     * </pre>
     *
     * <code>string remark = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 短信模板申请说明
     * </pre>
     *
     * <code>string remark = 4;</code>
     */
    public Builder setRemark(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      remark_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 短信模板申请说明
     * </pre>
     *
     * <code>string remark = 4;</code>
     */
    public Builder clearRemark() {
      
      remark_ = getDefaultInstance().getRemark();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 短信模板申请说明
     * </pre>
     *
     * <code>string remark = 4;</code>
     */
    public Builder setRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      remark_ = value;
      onChanged();
      return this;
    }

    private Object signName_ = "";
    /**
     * <pre>
     * title
     * </pre>
     *
     * <code>string SignName = 5;</code>
     */
    public String getSignName() {
      Object ref = signName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * title
     * </pre>
     *
     * <code>string SignName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignNameBytes() {
      Object ref = signName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * title
     * </pre>
     *
     * <code>string SignName = 5;</code>
     */
    public Builder setSignName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * title
     * </pre>
     *
     * <code>string SignName = 5;</code>
     */
    public Builder clearSignName() {
      
      signName_ = getDefaultInstance().getSignName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * title
     * </pre>
     *
     * <code>string SignName = 5;</code>
     */
    public Builder setSignNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:message.AddTemplateReq)
  }

  // @@protoc_insertion_point(class_scope:message.AddTemplateReq)
  private static final AddTemplateReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddTemplateReq();
  }

  public static AddTemplateReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddTemplateReq>
      PARSER = new com.google.protobuf.AbstractParser<AddTemplateReq>() {
    public AddTemplateReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddTemplateReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddTemplateReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddTemplateReq> getParserForType() {
    return PARSER;
  }

  public AddTemplateReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

