// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.config.Grpc.message;

public interface FindMessageByTopicRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.FindMessageByTopicResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>.message.Topic topic = 1;</code>
   */
  boolean hasTopic();
  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>.message.Topic topic = 1;</code>
   */
  Topic getTopic();
  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>.message.Topic topic = 1;</code>
   */
  TopicOrBuilder getTopicOrBuilder();

  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  java.util.List<Msg>
      getMsgListList();
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  Msg getMsgList(int index);
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  int getMsgListCount();
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  java.util.List<? extends MsgOrBuilder>
      getMsgListOrBuilderList();
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  MsgOrBuilder getMsgListOrBuilder(
      int index);
}
