// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.config.Grpc.message;

/**
 * Protobuf type {@code message.FindMessageByTopicResp}
 */
public  final class FindMessageByTopicResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:message.FindMessageByTopicResp)
    FindMessageByTopicRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindMessageByTopicResp.newBuilder() to construct.
  private FindMessageByTopicResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindMessageByTopicResp() {
    msgList_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FindMessageByTopicResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Topic.Builder subBuilder = null;
            if (topic_ != null) {
              subBuilder = topic_.toBuilder();
            }
            topic_ = input.readMessage(Topic.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(topic_);
              topic_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              msgList_ = new java.util.ArrayList<Msg>();
              mutable_bitField0_ |= 0x00000002;
            }
            msgList_.add(
                input.readMessage(Msg.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        msgList_ = java.util.Collections.unmodifiableList(msgList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageProto.internal_static_message_FindMessageByTopicResp_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageProto.internal_static_message_FindMessageByTopicResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FindMessageByTopicResp.class, Builder.class);
  }

  private int bitField0_;
  public static final int TOPIC_FIELD_NUMBER = 1;
  private Topic topic_;
  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>.message.Topic topic = 1;</code>
   */
  public boolean hasTopic() {
    return topic_ != null;
  }
  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>.message.Topic topic = 1;</code>
   */
  public Topic getTopic() {
    return topic_ == null ? Topic.getDefaultInstance() : topic_;
  }
  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>.message.Topic topic = 1;</code>
   */
  public TopicOrBuilder getTopicOrBuilder() {
    return getTopic();
  }

  public static final int MSGLIST_FIELD_NUMBER = 2;
  private java.util.List<Msg> msgList_;
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  public java.util.List<Msg> getMsgListList() {
    return msgList_;
  }
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  public java.util.List<? extends MsgOrBuilder>
      getMsgListOrBuilderList() {
    return msgList_;
  }
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  public int getMsgListCount() {
    return msgList_.size();
  }
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  public Msg getMsgList(int index) {
    return msgList_.get(index);
  }
  /**
   * <pre>
   * 消息列表
   * </pre>
   *
   * <code>repeated .message.Msg msgList = 2;</code>
   */
  public MsgOrBuilder getMsgListOrBuilder(
      int index) {
    return msgList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (topic_ != null) {
      output.writeMessage(1, getTopic());
    }
    for (int i = 0; i < msgList_.size(); i++) {
      output.writeMessage(2, msgList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (topic_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTopic());
    }
    for (int i = 0; i < msgList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, msgList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FindMessageByTopicResp)) {
      return super.equals(obj);
    }
    FindMessageByTopicResp other = (FindMessageByTopicResp) obj;

    boolean result = true;
    result = result && (hasTopic() == other.hasTopic());
    if (hasTopic()) {
      result = result && getTopic()
          .equals(other.getTopic());
    }
    result = result && getMsgListList()
        .equals(other.getMsgListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTopic()) {
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
    }
    if (getMsgListCount() > 0) {
      hash = (37 * hash) + MSGLIST_FIELD_NUMBER;
      hash = (53 * hash) + getMsgListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FindMessageByTopicResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FindMessageByTopicResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FindMessageByTopicResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FindMessageByTopicResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FindMessageByTopicResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FindMessageByTopicResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FindMessageByTopicResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FindMessageByTopicResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FindMessageByTopicResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FindMessageByTopicResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FindMessageByTopicResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FindMessageByTopicResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FindMessageByTopicResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code message.FindMessageByTopicResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:message.FindMessageByTopicResp)
      FindMessageByTopicRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_message_FindMessageByTopicResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_message_FindMessageByTopicResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FindMessageByTopicResp.class, Builder.class);
    }

    // Construct using gitspringboot.modules.message.FindMessageByTopicResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMsgListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (topicBuilder_ == null) {
        topic_ = null;
      } else {
        topic_ = null;
        topicBuilder_ = null;
      }
      if (msgListBuilder_ == null) {
        msgList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        msgListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageProto.internal_static_message_FindMessageByTopicResp_descriptor;
    }

    public FindMessageByTopicResp getDefaultInstanceForType() {
      return FindMessageByTopicResp.getDefaultInstance();
    }

    public FindMessageByTopicResp build() {
      FindMessageByTopicResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public FindMessageByTopicResp buildPartial() {
      FindMessageByTopicResp result = new FindMessageByTopicResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (topicBuilder_ == null) {
        result.topic_ = topic_;
      } else {
        result.topic_ = topicBuilder_.build();
      }
      if (msgListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          msgList_ = java.util.Collections.unmodifiableList(msgList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.msgList_ = msgList_;
      } else {
        result.msgList_ = msgListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FindMessageByTopicResp) {
        return mergeFrom((FindMessageByTopicResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FindMessageByTopicResp other) {
      if (other == FindMessageByTopicResp.getDefaultInstance()) return this;
      if (other.hasTopic()) {
        mergeTopic(other.getTopic());
      }
      if (msgListBuilder_ == null) {
        if (!other.msgList_.isEmpty()) {
          if (msgList_.isEmpty()) {
            msgList_ = other.msgList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMsgListIsMutable();
            msgList_.addAll(other.msgList_);
          }
          onChanged();
        }
      } else {
        if (!other.msgList_.isEmpty()) {
          if (msgListBuilder_.isEmpty()) {
            msgListBuilder_.dispose();
            msgListBuilder_ = null;
            msgList_ = other.msgList_;
            bitField0_ = (bitField0_ & ~0x00000002);
            msgListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMsgListFieldBuilder() : null;
          } else {
            msgListBuilder_.addAllMessages(other.msgList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FindMessageByTopicResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FindMessageByTopicResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Topic topic_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Topic, Topic.Builder, TopicOrBuilder> topicBuilder_;
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public boolean hasTopic() {
      return topicBuilder_ != null || topic_ != null;
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public Topic getTopic() {
      if (topicBuilder_ == null) {
        return topic_ == null ? Topic.getDefaultInstance() : topic_;
      } else {
        return topicBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public Builder setTopic(Topic value) {
      if (topicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        topic_ = value;
        onChanged();
      } else {
        topicBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public Builder setTopic(
        Topic.Builder builderForValue) {
      if (topicBuilder_ == null) {
        topic_ = builderForValue.build();
        onChanged();
      } else {
        topicBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public Builder mergeTopic(Topic value) {
      if (topicBuilder_ == null) {
        if (topic_ != null) {
          topic_ =
            Topic.newBuilder(topic_).mergeFrom(value).buildPartial();
        } else {
          topic_ = value;
        }
        onChanged();
      } else {
        topicBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public Builder clearTopic() {
      if (topicBuilder_ == null) {
        topic_ = null;
        onChanged();
      } else {
        topic_ = null;
        topicBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public Topic.Builder getTopicBuilder() {
      
      onChanged();
      return getTopicFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    public TopicOrBuilder getTopicOrBuilder() {
      if (topicBuilder_ != null) {
        return topicBuilder_.getMessageOrBuilder();
      } else {
        return topic_ == null ?
            Topic.getDefaultInstance() : topic_;
      }
    }
    /**
     * <pre>
     * 主题
     * </pre>
     *
     * <code>.message.Topic topic = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Topic, Topic.Builder, TopicOrBuilder>
        getTopicFieldBuilder() {
      if (topicBuilder_ == null) {
        topicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Topic, Topic.Builder, TopicOrBuilder>(
                getTopic(),
                getParentForChildren(),
                isClean());
        topic_ = null;
      }
      return topicBuilder_;
    }

    private java.util.List<Msg> msgList_ =
      java.util.Collections.emptyList();
    private void ensureMsgListIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        msgList_ = new java.util.ArrayList<Msg>(msgList_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Msg, Msg.Builder, MsgOrBuilder> msgListBuilder_;

    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public java.util.List<Msg> getMsgListList() {
      if (msgListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(msgList_);
      } else {
        return msgListBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public int getMsgListCount() {
      if (msgListBuilder_ == null) {
        return msgList_.size();
      } else {
        return msgListBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Msg getMsgList(int index) {
      if (msgListBuilder_ == null) {
        return msgList_.get(index);
      } else {
        return msgListBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder setMsgList(
        int index, Msg value) {
      if (msgListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgListIsMutable();
        msgList_.set(index, value);
        onChanged();
      } else {
        msgListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder setMsgList(
        int index, Msg.Builder builderForValue) {
      if (msgListBuilder_ == null) {
        ensureMsgListIsMutable();
        msgList_.set(index, builderForValue.build());
        onChanged();
      } else {
        msgListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder addMsgList(Msg value) {
      if (msgListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgListIsMutable();
        msgList_.add(value);
        onChanged();
      } else {
        msgListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder addMsgList(
        int index, Msg value) {
      if (msgListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMsgListIsMutable();
        msgList_.add(index, value);
        onChanged();
      } else {
        msgListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder addMsgList(
        Msg.Builder builderForValue) {
      if (msgListBuilder_ == null) {
        ensureMsgListIsMutable();
        msgList_.add(builderForValue.build());
        onChanged();
      } else {
        msgListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder addMsgList(
        int index, Msg.Builder builderForValue) {
      if (msgListBuilder_ == null) {
        ensureMsgListIsMutable();
        msgList_.add(index, builderForValue.build());
        onChanged();
      } else {
        msgListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder addAllMsgList(
        Iterable<? extends Msg> values) {
      if (msgListBuilder_ == null) {
        ensureMsgListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, msgList_);
        onChanged();
      } else {
        msgListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder clearMsgList() {
      if (msgListBuilder_ == null) {
        msgList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        msgListBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Builder removeMsgList(int index) {
      if (msgListBuilder_ == null) {
        ensureMsgListIsMutable();
        msgList_.remove(index);
        onChanged();
      } else {
        msgListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Msg.Builder getMsgListBuilder(
        int index) {
      return getMsgListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public MsgOrBuilder getMsgListOrBuilder(
        int index) {
      if (msgListBuilder_ == null) {
        return msgList_.get(index);  } else {
        return msgListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public java.util.List<? extends MsgOrBuilder>
         getMsgListOrBuilderList() {
      if (msgListBuilder_ != null) {
        return msgListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(msgList_);
      }
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Msg.Builder addMsgListBuilder() {
      return getMsgListFieldBuilder().addBuilder(
          Msg.getDefaultInstance());
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public Msg.Builder addMsgListBuilder(
        int index) {
      return getMsgListFieldBuilder().addBuilder(
          index, Msg.getDefaultInstance());
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .message.Msg msgList = 2;</code>
     */
    public java.util.List<Msg.Builder>
         getMsgListBuilderList() {
      return getMsgListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Msg, Msg.Builder, MsgOrBuilder>
        getMsgListFieldBuilder() {
      if (msgListBuilder_ == null) {
        msgListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Msg, Msg.Builder, MsgOrBuilder>(
                msgList_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        msgList_ = null;
      }
      return msgListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:message.FindMessageByTopicResp)
  }

  // @@protoc_insertion_point(class_scope:message.FindMessageByTopicResp)
  private static final FindMessageByTopicResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FindMessageByTopicResp();
  }

  public static FindMessageByTopicResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindMessageByTopicResp>
      PARSER = new com.google.protobuf.AbstractParser<FindMessageByTopicResp>() {
    public FindMessageByTopicResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FindMessageByTopicResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FindMessageByTopicResp> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FindMessageByTopicResp> getParserForType() {
    return PARSER;
  }

  public FindMessageByTopicResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

