// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.config.Grpc.message;

/**
 * <pre>
 * 发送消息
 * </pre>
 *
 * Protobuf type {@code message.SendMsgReq}
 */
public  final class SendMsgReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:message.SendMsgReq)
    SendMsgReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendMsgReq.newBuilder() to construct.
  private SendMsgReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendMsgReq() {
    topicId_ = "";
    body_ = "";
    from_ = "";
    to_ = "";
    attachmentLink_ = "";
    link_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SendMsgReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            topicId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            from_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            to_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            attachmentLink_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            link_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageProto.internal_static_message_SendMsgReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageProto.internal_static_message_SendMsgReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SendMsgReq.class, Builder.class);
  }

  public static final int TOPICID_FIELD_NUMBER = 2;
  private volatile Object topicId_;
  /**
   * <pre>
   * 所属主题Id
   * </pre>
   *
   * <code>string topicId = 2;</code>
   */
  public String getTopicId() {
    Object ref = topicId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      topicId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 所属主题Id
   * </pre>
   *
   * <code>string topicId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTopicIdBytes() {
    Object ref = topicId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      topicId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 3;
  private volatile Object body_;
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string body = 3;</code>
   */
  public String getBody() {
    Object ref = body_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string body = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBodyBytes() {
    Object ref = body_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_FIELD_NUMBER = 4;
  private volatile Object from_;
  /**
   * <pre>
   * 发起方
   * </pre>
   *
   * <code>string from = 4;</code>
   */
  public String getFrom() {
    Object ref = from_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发起方
   * </pre>
   *
   * <code>string from = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFromBytes() {
    Object ref = from_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FIELD_NUMBER = 5;
  private volatile Object to_;
  /**
   * <pre>
   * 接收方
   * </pre>
   *
   * <code>string to = 5;</code>
   */
  public String getTo() {
    Object ref = to_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      to_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 接收方
   * </pre>
   *
   * <code>string to = 5;</code>
   */
  public com.google.protobuf.ByteString
      getToBytes() {
    Object ref = to_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      to_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTACHMENTLINK_FIELD_NUMBER = 6;
  private volatile Object attachmentLink_;
  /**
   * <pre>
   * 附件链接
   * </pre>
   *
   * <code>string attachmentLink = 6;</code>
   */
  public String getAttachmentLink() {
    Object ref = attachmentLink_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      attachmentLink_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 附件链接
   * </pre>
   *
   * <code>string attachmentLink = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAttachmentLinkBytes() {
    Object ref = attachmentLink_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      attachmentLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINK_FIELD_NUMBER = 7;
  private volatile Object link_;
  /**
   * <pre>
   * 入口关联链接
   * </pre>
   *
   * <code>string Link = 7;</code>
   */
  public String getLink() {
    Object ref = link_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      link_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 入口关联链接
   * </pre>
   *
   * <code>string Link = 7;</code>
   */
  public com.google.protobuf.ByteString
      getLinkBytes() {
    Object ref = link_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      link_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTopicIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topicId_);
    }
    if (!getBodyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, body_);
    }
    if (!getFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, from_);
    }
    if (!getToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, to_);
    }
    if (!getAttachmentLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, attachmentLink_);
    }
    if (!getLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, link_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTopicIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topicId_);
    }
    if (!getBodyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, body_);
    }
    if (!getFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, from_);
    }
    if (!getToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, to_);
    }
    if (!getAttachmentLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, attachmentLink_);
    }
    if (!getLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, link_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SendMsgReq)) {
      return super.equals(obj);
    }
    SendMsgReq other = (SendMsgReq) obj;

    boolean result = true;
    result = result && getTopicId()
        .equals(other.getTopicId());
    result = result && getBody()
        .equals(other.getBody());
    result = result && getFrom()
        .equals(other.getFrom());
    result = result && getTo()
        .equals(other.getTo());
    result = result && getAttachmentLink()
        .equals(other.getAttachmentLink());
    result = result && getLink()
        .equals(other.getLink());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPICID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo().hashCode();
    hash = (37 * hash) + ATTACHMENTLINK_FIELD_NUMBER;
    hash = (53 * hash) + getAttachmentLink().hashCode();
    hash = (37 * hash) + LINK_FIELD_NUMBER;
    hash = (53 * hash) + getLink().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SendMsgReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendMsgReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendMsgReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendMsgReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendMsgReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SendMsgReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SendMsgReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SendMsgReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SendMsgReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SendMsgReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SendMsgReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SendMsgReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SendMsgReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 发送消息
   * </pre>
   *
   * Protobuf type {@code message.SendMsgReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:message.SendMsgReq)
      SendMsgReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_message_SendMsgReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_message_SendMsgReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SendMsgReq.class, Builder.class);
    }

    // Construct using gitspringboot.modules.message.SendMsgReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      topicId_ = "";

      body_ = "";

      from_ = "";

      to_ = "";

      attachmentLink_ = "";

      link_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageProto.internal_static_message_SendMsgReq_descriptor;
    }

    public SendMsgReq getDefaultInstanceForType() {
      return SendMsgReq.getDefaultInstance();
    }

    public SendMsgReq build() {
      SendMsgReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public SendMsgReq buildPartial() {
      SendMsgReq result = new SendMsgReq(this);
      result.topicId_ = topicId_;
      result.body_ = body_;
      result.from_ = from_;
      result.to_ = to_;
      result.attachmentLink_ = attachmentLink_;
      result.link_ = link_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SendMsgReq) {
        return mergeFrom((SendMsgReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SendMsgReq other) {
      if (other == SendMsgReq.getDefaultInstance()) return this;
      if (!other.getTopicId().isEmpty()) {
        topicId_ = other.topicId_;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (!other.getTo().isEmpty()) {
        to_ = other.to_;
        onChanged();
      }
      if (!other.getAttachmentLink().isEmpty()) {
        attachmentLink_ = other.attachmentLink_;
        onChanged();
      }
      if (!other.getLink().isEmpty()) {
        link_ = other.link_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SendMsgReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SendMsgReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object topicId_ = "";
    /**
     * <pre>
     * 所属主题Id
     * </pre>
     *
     * <code>string topicId = 2;</code>
     */
    public String getTopicId() {
      Object ref = topicId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topicId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 所属主题Id
     * </pre>
     *
     * <code>string topicId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicIdBytes() {
      Object ref = topicId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 所属主题Id
     * </pre>
     *
     * <code>string topicId = 2;</code>
     */
    public Builder setTopicId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topicId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属主题Id
     * </pre>
     *
     * <code>string topicId = 2;</code>
     */
    public Builder clearTopicId() {
      
      topicId_ = getDefaultInstance().getTopicId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属主题Id
     * </pre>
     *
     * <code>string topicId = 2;</code>
     */
    public Builder setTopicIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topicId_ = value;
      onChanged();
      return this;
    }

    private Object body_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string body = 3;</code>
     */
    public String getBody() {
      Object ref = body_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string body = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string body = 3;</code>
     */
    public Builder setBody(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string body = 3;</code>
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string body = 3;</code>
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private Object from_ = "";
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string from = 4;</code>
     */
    public String getFrom() {
      Object ref = from_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string from = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string from = 4;</code>
     */
    public Builder setFrom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string from = 4;</code>
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发起方
     * </pre>
     *
     * <code>string from = 4;</code>
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private Object to_ = "";
    /**
     * <pre>
     * 接收方
     * </pre>
     *
     * <code>string to = 5;</code>
     */
    public String getTo() {
      Object ref = to_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 接收方
     * </pre>
     *
     * <code>string to = 5;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 接收方
     * </pre>
     *
     * <code>string to = 5;</code>
     */
    public Builder setTo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收方
     * </pre>
     *
     * <code>string to = 5;</code>
     */
    public Builder clearTo() {
      
      to_ = getDefaultInstance().getTo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收方
     * </pre>
     *
     * <code>string to = 5;</code>
     */
    public Builder setToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      to_ = value;
      onChanged();
      return this;
    }

    private Object attachmentLink_ = "";
    /**
     * <pre>
     * 附件链接
     * </pre>
     *
     * <code>string attachmentLink = 6;</code>
     */
    public String getAttachmentLink() {
      Object ref = attachmentLink_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        attachmentLink_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 附件链接
     * </pre>
     *
     * <code>string attachmentLink = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAttachmentLinkBytes() {
      Object ref = attachmentLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        attachmentLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 附件链接
     * </pre>
     *
     * <code>string attachmentLink = 6;</code>
     */
    public Builder setAttachmentLink(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      attachmentLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 附件链接
     * </pre>
     *
     * <code>string attachmentLink = 6;</code>
     */
    public Builder clearAttachmentLink() {
      
      attachmentLink_ = getDefaultInstance().getAttachmentLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 附件链接
     * </pre>
     *
     * <code>string attachmentLink = 6;</code>
     */
    public Builder setAttachmentLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      attachmentLink_ = value;
      onChanged();
      return this;
    }

    private Object link_ = "";
    /**
     * <pre>
     * 入口关联链接
     * </pre>
     *
     * <code>string Link = 7;</code>
     */
    public String getLink() {
      Object ref = link_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        link_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 入口关联链接
     * </pre>
     *
     * <code>string Link = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 入口关联链接
     * </pre>
     *
     * <code>string Link = 7;</code>
     */
    public Builder setLink(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      link_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 入口关联链接
     * </pre>
     *
     * <code>string Link = 7;</code>
     */
    public Builder clearLink() {
      
      link_ = getDefaultInstance().getLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 入口关联链接
     * </pre>
     *
     * <code>string Link = 7;</code>
     */
    public Builder setLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      link_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:message.SendMsgReq)
  }

  // @@protoc_insertion_point(class_scope:message.SendMsgReq)
  private static final SendMsgReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SendMsgReq();
  }

  public static SendMsgReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMsgReq>
      PARSER = new com.google.protobuf.AbstractParser<SendMsgReq>() {
    public SendMsgReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SendMsgReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendMsgReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SendMsgReq> getParserForType() {
    return PARSER;
  }

  public SendMsgReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

