// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.config.Grpc.message;

public interface TopicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.Topic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 主题Id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <pre>
   * 主题Id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 主题名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <pre>
   * 主题名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 入口关联链接
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  String getLink();
  /**
   * <pre>
   * 入口关联链接
   * </pre>
   *
   * <code>string link = 3;</code>
   */
  com.google.protobuf.ByteString
      getLinkBytes();

  /**
   * <pre>
   * 发起方
   * </pre>
   *
   * <code>string from = 4;</code>
   */
  String getFrom();
  /**
   * <pre>
   * 发起方
   * </pre>
   *
   * <code>string from = 4;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   * 接收方
   * </pre>
   *
   * <code>string to = 5;</code>
   */
  String getTo();
  /**
   * <pre>
   * 接收方
   * </pre>
   *
   * <code>string to = 5;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <pre>
   * 发起方已读
   * </pre>
   *
   * <code>bool fromMarkRead = 6;</code>
   */
  boolean getFromMarkRead();

  /**
   * <pre>
   * 接收方已读
   * </pre>
   *
   * <code>bool toMarkRead = 7;</code>
   */
  boolean getToMarkRead();

  /**
   * <pre>
   * 创建时间
   * </pre>
   *
   * <code>int64 createdAt = 8;</code>
   */
  long getCreatedAt();
}
