// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface AddTemplateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.AddTemplateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 模版类型
   * </pre>
   *
   * <code>.message.TemplateType templateType = 1;</code>
   */
  int getTemplateTypeValue();
  /**
   * <pre>
   * 模版类型
   * </pre>
   *
   * <code>.message.TemplateType templateType = 1;</code>
   */
  TemplateType getTemplateType();

  /**
   * <pre>
   * 1~30字符
   * </pre>
   *
   * <code>string templateName = 2;</code>
   */
  String getTemplateName();
  /**
   * <pre>
   * 1~30字符
   * </pre>
   *
   * <code>string templateName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTemplateNameBytes();

  /**
   * <pre>
   * 1~500字符内
   * </pre>
   *
   * <code>string templateContent = 3;</code>
   */
  String getTemplateContent();
  /**
   * <pre>
   * 1~500字符内
   * </pre>
   *
   * <code>string templateContent = 3;</code>
   */
  com.google.protobuf.ByteString
      getTemplateContentBytes();

  /**
   * <pre>
   * 短信模板申请说明
   * </pre>
   *
   * <code>string remark = 4;</code>
   */
  String getRemark();
  /**
   * <pre>
   * 短信模板申请说明
   * </pre>
   *
   * <code>string remark = 4;</code>
   */
  com.google.protobuf.ByteString
      getRemarkBytes();

  /**
   * <pre>
   * title
   * </pre>
   *
   * <code>string SignName = 5;</code>
   */
  String getSignName();
  /**
   * <pre>
   * title
   * </pre>
   *
   * <code>string SignName = 5;</code>
   */
  com.google.protobuf.ByteString
      getSignNameBytes();
}
