// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface CheckStatusRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.CheckStatusResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.message.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.message.Status status = 1;</code>
   */
  Status getStatus();

  /**
   * <code>string reason = 2;</code>
   */
  String getReason();
  /**
   * <code>string reason = 2;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
