// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface DeleteTemplateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.DeleteTemplateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 模版代码
   * </pre>
   *
   * <code>string templateCode = 1;</code>
   */
  String getTemplateCode();
  /**
   * <pre>
   * 模版代码
   * </pre>
   *
   * <code>string templateCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemplateCodeBytes();
}
