// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface DeleteTemplateRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.DeleteTemplateResp)
    com.google.protobuf.MessageOrBuilder {
}
