// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface FindTopicByUserReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.FindTopicByUserReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.message.Pagination pagination = 1;</code>
   */
  boolean hasPagination();
  /**
   * <code>.message.Pagination pagination = 1;</code>
   */
  Pagination getPagination();
  /**
   * <code>.message.Pagination pagination = 1;</code>
   */
  PaginationOrBuilder getPaginationOrBuilder();

  /**
   * <code>string userId = 2;</code>
   */
  String getUserId();
  /**
   * <code>string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
