// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface GetUnReadMsgCountRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.GetUnReadMsgCountResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 count = 1;</code>
   */
  long getCount();
}
