// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface GetUnReadTopicCountReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.GetUnReadTopicCountReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string UserId = 1;</code>
   */
  String getUserId();
  /**
   * <code>string UserId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
