// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface GetUnReadTopicCountRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.GetUnReadTopicCountResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 count = 1;</code>
   */
  long getCount();
}
