// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface ListTemplateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.ListTemplateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>.message.Pagination pagination = 1;</code>
   */
  boolean hasPagination();
  /**
   * <pre>
   * </pre>
   *
   * <code>.message.Pagination pagination = 1;</code>
   */
  Pagination getPagination();
  /**
   * <pre>
   * </pre>
   *
   * <code>.message.Pagination pagination = 1;</code>
   */
  PaginationOrBuilder getPaginationOrBuilder();
}
