// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface ListTemplateRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.ListTemplateResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 total = 1;</code>
   */
  long getTotal();

  /**
   * <pre>
   * 模版列表
   * </pre>
   *
   * <code>repeated .message.Template templateList = 2;</code>
   */
  java.util.List<Template>
      getTemplateListList();
  /**
   * <pre>
   * 模版列表
   * </pre>
   *
   * <code>repeated .message.Template templateList = 2;</code>
   */
  Template getTemplateList(int index);
  /**
   * <pre>
   * 模版列表
   * </pre>
   *
   * <code>repeated .message.Template templateList = 2;</code>
   */
  int getTemplateListCount();
  /**
   * <pre>
   * 模版列表
   * </pre>
   *
   * <code>repeated .message.Template templateList = 2;</code>
   */
  java.util.List<? extends TemplateOrBuilder>
      getTemplateListOrBuilderList();
  /**
   * <pre>
   * 模版列表
   * </pre>
   *
   * <code>repeated .message.Template templateList = 2;</code>
   */
  TemplateOrBuilder getTemplateListOrBuilder(
      int index);
}
