// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Pagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Pagination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Template_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Template_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_AddTemplateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_AddTemplateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_AddTemplateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_AddTemplateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendSmsReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendSmsReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendSmsReq_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendSmsReq_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendSmsResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendSmsResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendEmailReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendEmailReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendEmailReq_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendEmailReq_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendEmailResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendEmailResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ListTemplateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ListTemplateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_ListTemplateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_ListTemplateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_DeleteTemplateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_DeleteTemplateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_DeleteTemplateResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_DeleteTemplateResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_CheckStatusReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_CheckStatusReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Topic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Topic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendMsgReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendMsgReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_SendMsgResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_SendMsgResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GetUnReadMsgCountReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GetUnReadMsgCountReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GetUnReadMsgCountResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GetUnReadMsgCountResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GetUnReadTopicCountReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GetUnReadTopicCountReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_GetUnReadTopicCountResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_GetUnReadTopicCountResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_FindMessageByTopicReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_FindMessageByTopicReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_FindMessageByTopicResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_FindMessageByTopicResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_FindTopicByUserReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_FindTopicByUserReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_FindTopicByUserResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_FindTopicByUserResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_CheckStatusResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_CheckStatusResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"1\n\nPagination\022\021" +
      "\n\tpageIndex\030\001 \001(\004\022\020\n\010pageSize\030\002 \001(\004\"\262\001\n\010" +
      "Template\022\n\n\002id\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022+\n\006st" +
      "atus\030\003 \001(\0162\033.message.TemplateStatusType\022" +
      "\014\n\004name\030\004 \001(\t\022\014\n\004type\030\005 \001(\003\022\016\n\006reason\030\006 " +
      "\001(\t\022\017\n\007content\030\007 \001(\t\022\020\n\010createAt\030\010 \001(\003\022\020" +
      "\n\010signName\030\t \001(\t\"\216\001\n\016AddTemplateReq\022+\n\014t" +
      "emplateType\030\001 \001(\0162\025.message.TemplateType" +
      "\022\024\n\014templateName\030\002 \001(\t\022\027\n\017templateConten" +
      "t\030\003 \001(\t\022\016\n\006remark\030\004 \001(\t\022\020\n\010SignName\030\005 \001(" +
      "\t\"\'\n\017AddTemplateResp\022\024\n\014templateCode\030\001 \001" +
      "(\t\"\222\001\n\nSendSmsReq\022\024\n\014templateCode\030\001 \001(\t\022" +
      "/\n\006params\030\002 \003(\0132\037.message.SendSmsReq.Par" +
      "amsEntry\022\016\n\006mobile\030\003 \001(\t\032-\n\013ParamsEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\033\n\013SendS" +
      "msResp\022\014\n\004code\030\001 \001(\t\"\225\001\n\014SendEmailReq\022\024\n" +
      "\014templateCode\030\001 \001(\t\0221\n\006params\030\002 \003(\0132!.me" +
      "ssage.SendEmailReq.ParamsEntry\022\r\n\005Email\030" +
      "\003 \001(\t\032-\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001\"\035\n\rSendEmailResp\022\014\n\004code\030\001 " +
      "\001(\t\":\n\017ListTemplateReq\022\'\n\npagination\030\001 \001" +
      "(\0132\023.message.Pagination\"J\n\020ListTemplateR" +
      "esp\022\r\n\005total\030\001 \001(\004\022\'\n\014templateList\030\002 \003(\013" +
      "2\021.message.Template\")\n\021DeleteTemplateReq" +
      "\022\024\n\014templateCode\030\001 \001(\t\"\024\n\022DeleteTemplate" +
      "Resp\"\036\n\016CheckStatusReq\022\014\n\004code\030\001 \001(\t\"\206\001\n" +
      "\005Topic\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004link" +
      "\030\003 \001(\t\022\014\n\004from\030\004 \001(\t\022\n\n\002to\030\005 \001(\t\022\024\n\014from" +
      "MarkRead\030\006 \001(\010\022\022\n\ntoMarkRead\030\007 \001(\010\022\021\n\tcr" +
      "eatedAt\030\010 \001(\003\"\225\001\n\003Msg\022\n\n\002id\030\001 \001(\t\022\017\n\007top" +
      "icId\030\002 \001(\t\022\014\n\004body\030\003 \001(\t\022\014\n\004from\030\004 \001(\t\022\n" +
      "\n\002to\030\005 \001(\t\022\014\n\004link\030\006 \001(\t\022\026\n\016attachmentLi" +
      "nk\030\007 \003(\t\022\020\n\010markRead\030\010 \001(\010\022\021\n\tcreatedAt\030" +
      "\t \001(\003\"k\n\nSendMsgReq\022\017\n\007topicId\030\002 \001(\t\022\014\n\004" +
      "body\030\003 \001(\t\022\014\n\004from\030\004 \001(\t\022\n\n\002to\030\005 \001(\t\022\026\n\016" +
      "attachmentLink\030\006 \001(\t\022\014\n\004Link\030\007 \001(\t\"-\n\013Se" +
      "ndMsgResp\022\r\n\005msgId\030\001 \001(\t\022\017\n\007topicId\030\002 \001(" +
      "\t\"&\n\024GetUnReadMsgCountReq\022\016\n\006userId\030\001 \001(" +
      "\t\"&\n\025GetUnReadMsgCountResp\022\r\n\005count\030\001 \001(" +
      "\004\"(\n\026GetUnReadTopicCountReq\022\016\n\006UserId\030\001 " +
      "\001(\t\"(\n\027GetUnReadTopicCountResp\022\r\n\005count\030" +
      "\001 \001(\004\"(\n\025FindMessageByTopicReq\022\017\n\007topicI" +
      "d\030\001 \001(\t\"V\n\026FindMessageByTopicResp\022\035\n\005top" +
      "ic\030\001 \001(\0132\016.message.Topic\022\035\n\007msgList\030\002 \003(" +
      "\0132\014.message.Msg\"M\n\022FindTopicByUserReq\022\'\n" +
      "\npagination\030\001 \001(\0132\023.message.Pagination\022\016" +
      "\n\006userId\030\002 \001(\t\"G\n\023FindTopicByUserResp\022\r\n" +
      "\005total\030\001 \001(\004\022!\n\ttopicList\030\002 \003(\0132\016.messag" +
      "e.Topic\"B\n\017CheckStatusResp\022\037\n\006status\030\001 \001" +
      "(\0162\017.message.Status\022\016\n\006reason\030\002 \001(\t*T\n\022T" +
      "emplateStatusType\022\010\n\004none\020\000\022\010\n\004init\020\001\022\010\n" +
      "\004pass\020\002\022\010\n\004deny\020\003\022\n\n\006cancel\020\004\022\n\n\006delete\020" +
      "\005*U\n\014TemplateType\022\017\n\013verify_code\020\000\022\n\n\006no" +
      "tify\020\001\022\r\n\tpromotion\020\002\022\031\n\025international_m" +
      "essage\020\003*/\n\006Status\022\013\n\007sending\020\000\022\013\n\007succe" +
      "ss\020\001\022\013\n\007failure\020\0022\230\006\n\007message\0224\n\007SendSms" +
      "\022\023.message.SendSmsReq\032\024.message.SendSmsR" +
      "esp\022:\n\tSendEmail\022\025.message.SendEmailReq\032" +
      "\026.message.SendEmailResp\022@\n\013CheckStatus\022\027" +
      ".message.CheckStatusReq\032\030.message.CheckS" +
      "tatusResp\022@\n\013AddTemplate\022\027.message.AddTe" +
      "mplateReq\032\030.message.AddTemplateResp\022C\n\014L" +
      "istTemplate\022\030.message.ListTemplateReq\032\031." +
      "message.ListTemplateResp\022I\n\016DeleteTempla" +
      "te\022\032.message.DeleteTemplateReq\032\033.message" +
      ".DeleteTemplateResp\0224\n\007SendMsg\022\023.message" +
      ".SendMsgReq\032\024.message.SendMsgResp\022U\n\022Fin" +
      "dMessageByTopic\022\036.message.FindMessageByT" +
      "opicReq\032\037.message.FindMessageByTopicResp" +
      "\022L\n\017FindTopicByUser\022\033.message.FindTopicB" +
      "yUserReq\032\034.message.FindTopicByUserResp\022X" +
      "\n\023GetUnReadTopicCount\022\037.message.GetUnRea" +
      "dTopicCountReq\032 .message.GetUnReadTopicC" +
      "ountResp\022R\n\021GetUnReadMsgCount\022\035.message." +
      "GetUnReadMsgCountReq\032\036.message.GetUnRead" +
      "MsgCountRespB/\n\035gitspringboot.modules.me" +
      "ssageB\014MessageProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Pagination_descriptor,
        new String[] { "PageIndex", "PageSize", });
    internal_static_message_Template_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_Template_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Template_descriptor,
        new String[] { "Id", "Code", "Status", "Name", "Type", "Reason", "Content", "CreateAt", "SignName", });
    internal_static_message_AddTemplateReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_AddTemplateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_AddTemplateReq_descriptor,
        new String[] { "TemplateType", "TemplateName", "TemplateContent", "Remark", "SignName", });
    internal_static_message_AddTemplateResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_message_AddTemplateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_AddTemplateResp_descriptor,
        new String[] { "TemplateCode", });
    internal_static_message_SendSmsReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_message_SendSmsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendSmsReq_descriptor,
        new String[] { "TemplateCode", "Params", "Mobile", });
    internal_static_message_SendSmsReq_ParamsEntry_descriptor =
      internal_static_message_SendSmsReq_descriptor.getNestedTypes().get(0);
    internal_static_message_SendSmsReq_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendSmsReq_ParamsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_message_SendSmsResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_message_SendSmsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendSmsResp_descriptor,
        new String[] { "Code", });
    internal_static_message_SendEmailReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_message_SendEmailReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendEmailReq_descriptor,
        new String[] { "TemplateCode", "Params", "Email", });
    internal_static_message_SendEmailReq_ParamsEntry_descriptor =
      internal_static_message_SendEmailReq_descriptor.getNestedTypes().get(0);
    internal_static_message_SendEmailReq_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendEmailReq_ParamsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_message_SendEmailResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_message_SendEmailResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendEmailResp_descriptor,
        new String[] { "Code", });
    internal_static_message_ListTemplateReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_message_ListTemplateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ListTemplateReq_descriptor,
        new String[] { "Pagination", });
    internal_static_message_ListTemplateResp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_message_ListTemplateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_ListTemplateResp_descriptor,
        new String[] { "Total", "TemplateList", });
    internal_static_message_DeleteTemplateReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_message_DeleteTemplateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_DeleteTemplateReq_descriptor,
        new String[] { "TemplateCode", });
    internal_static_message_DeleteTemplateResp_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_message_DeleteTemplateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_DeleteTemplateResp_descriptor,
        new String[] { });
    internal_static_message_CheckStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_message_CheckStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_CheckStatusReq_descriptor,
        new String[] { "Code", });
    internal_static_message_Topic_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_message_Topic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Topic_descriptor,
        new String[] { "Id", "Name", "Link", "From", "To", "FromMarkRead", "ToMarkRead", "CreatedAt", });
    internal_static_message_Msg_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_message_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Msg_descriptor,
        new String[] { "Id", "TopicId", "Body", "From", "To", "Link", "AttachmentLink", "MarkRead", "CreatedAt", });
    internal_static_message_SendMsgReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_message_SendMsgReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendMsgReq_descriptor,
        new String[] { "TopicId", "Body", "From", "To", "AttachmentLink", "Link", });
    internal_static_message_SendMsgResp_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_message_SendMsgResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_SendMsgResp_descriptor,
        new String[] { "MsgId", "TopicId", });
    internal_static_message_GetUnReadMsgCountReq_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_message_GetUnReadMsgCountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GetUnReadMsgCountReq_descriptor,
        new String[] { "UserId", });
    internal_static_message_GetUnReadMsgCountResp_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_message_GetUnReadMsgCountResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GetUnReadMsgCountResp_descriptor,
        new String[] { "Count", });
    internal_static_message_GetUnReadTopicCountReq_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_message_GetUnReadTopicCountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GetUnReadTopicCountReq_descriptor,
        new String[] { "UserId", });
    internal_static_message_GetUnReadTopicCountResp_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_message_GetUnReadTopicCountResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_GetUnReadTopicCountResp_descriptor,
        new String[] { "Count", });
    internal_static_message_FindMessageByTopicReq_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_message_FindMessageByTopicReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_FindMessageByTopicReq_descriptor,
        new String[] { "TopicId", });
    internal_static_message_FindMessageByTopicResp_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_message_FindMessageByTopicResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_FindMessageByTopicResp_descriptor,
        new String[] { "Topic", "MsgList", });
    internal_static_message_FindTopicByUserReq_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_message_FindTopicByUserReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_FindTopicByUserReq_descriptor,
        new String[] { "Pagination", "UserId", });
    internal_static_message_FindTopicByUserResp_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_message_FindTopicByUserResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_FindTopicByUserResp_descriptor,
        new String[] { "Total", "TopicList", });
    internal_static_message_CheckStatusResp_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_message_CheckStatusResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_CheckStatusResp_descriptor,
        new String[] { "Status", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
