// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 发送消息时忽略字段
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <pre>
   * 发送消息时忽略字段
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 所属主题Id
   * </pre>
   *
   * <code>string topicId = 2;</code>
   */
  String getTopicId();
  /**
   * <pre>
   * 所属主题Id
   * </pre>
   *
   * <code>string topicId = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicIdBytes();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string body = 3;</code>
   */
  String getBody();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string body = 3;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <pre>
   * 发起方
   * </pre>
   *
   * <code>string from = 4;</code>
   */
  String getFrom();
  /**
   * <pre>
   * 发起方
   * </pre>
   *
   * <code>string from = 4;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   * 接收方
   * </pre>
   *
   * <code>string to = 5;</code>
   */
  String getTo();
  /**
   * <pre>
   * 接收方
   * </pre>
   *
   * <code>string to = 5;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string link = 6;</code>
   */
  String getLink();
  /**
   * <code>string link = 6;</code>
   */
  com.google.protobuf.ByteString
      getLinkBytes();

  /**
   * <pre>
   * 附件链接
   * </pre>
   *
   * <code>repeated string attachmentLink = 7;</code>
   */
  java.util.List<String>
      getAttachmentLinkList();
  /**
   * <pre>
   * 附件链接
   * </pre>
   *
   * <code>repeated string attachmentLink = 7;</code>
   */
  int getAttachmentLinkCount();
  /**
   * <pre>
   * 附件链接
   * </pre>
   *
   * <code>repeated string attachmentLink = 7;</code>
   */
  String getAttachmentLink(int index);
  /**
   * <pre>
   * 附件链接
   * </pre>
   *
   * <code>repeated string attachmentLink = 7;</code>
   */
  com.google.protobuf.ByteString
      getAttachmentLinkBytes(int index);

  /**
   * <pre>
   * 是否已读
   * </pre>
   *
   * <code>bool markRead = 8;</code>
   */
  boolean getMarkRead();

  /**
   * <pre>
   * 创建时间
   * </pre>
   *
   * <code>int64 createdAt = 9;</code>
   */
  long getCreatedAt();
}
