// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 分页页数
   * </pre>
   *
   * <code>uint64 pageIndex = 1;</code>
   */
  long getPageIndex();

  /**
   * <pre>
   * 每页数量
   * </pre>
   *
   * <code>uint64 pageSize = 2;</code>
   */
  long getPageSize();
}
