// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface SendMsgRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.SendMsgResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息Id
   * </pre>
   *
   * <code>string msgId = 1;</code>
   */
  String getMsgId();
  /**
   * <pre>
   * 消息Id
   * </pre>
   *
   * <code>string msgId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <pre>
   * 主题Id
   * </pre>
   *
   * <code>string topicId = 2;</code>
   */
  String getTopicId();
  /**
   * <pre>
   * 主题Id
   * </pre>
   *
   * <code>string topicId = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicIdBytes();
}
