// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface SendSmsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.SendSmsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 模版代码
   * </pre>
   *
   * <code>string templateCode = 1;</code>
   */
  String getTemplateCode();
  /**
   * <pre>
   * 模版代码
   * </pre>
   *
   * <code>string templateCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemplateCodeBytes();

  /**
   * <pre>
   * 模版参数
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */
  int getParamsCount();
  /**
   * <pre>
   * 模版参数
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */
  boolean containsParams(
      String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getParams();
  /**
   * <pre>
   * 模版参数
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */
  java.util.Map<String, String>
  getParamsMap();
  /**
   * <pre>
   * 模版参数
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */

  String getParamsOrDefault(
      String key,
      String defaultValue);
  /**
   * <pre>
   * 模版参数
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */

  String getParamsOrThrow(
      String key);

  /**
   * <pre>
   * 手机号
   * </pre>
   *
   * <code>string mobile = 3;</code>
   */
  String getMobile();
  /**
   * <pre>
   * 手机号
   * </pre>
   *
   * <code>string mobile = 3;</code>
   */
  com.google.protobuf.ByteString
      getMobileBytes();
}
