// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package gitspringboot.modules.message;

public interface TemplateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.Template)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 模版代码
   * </pre>
   *
   * <code>string code = 2;</code>
   */
  String getCode();
  /**
   * <pre>
   * 模版代码
   * </pre>
   *
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * 审批状态
   * </pre>
   *
   * <code>.message.TemplateStatusType status = 3;</code>
   */
  int getStatusValue();
  /**
   * <pre>
   * 审批状态
   * </pre>
   *
   * <code>.message.TemplateStatusType status = 3;</code>
   */
  TemplateStatusType getStatus();

  /**
   * <pre>
   * 模版名称
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  String getName();
  /**
   * <pre>
   * 模版名称
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 模版类型
   * </pre>
   *
   * <code>int64 type = 5;</code>
   */
  long getType();

  /**
   * <pre>
   * 原因
   * </pre>
   *
   * <code>string reason = 6;</code>
   */
  String getReason();
  /**
   * <pre>
   * 原因
   * </pre>
   *
   * <code>string reason = 6;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <pre>
   * 模版内容
   * </pre>
   *
   * <code>string content = 7;</code>
   */
  String getContent();
  /**
   * <pre>
   * 模版内容
   * </pre>
   *
   * <code>string content = 7;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 创建时间
   * </pre>
   *
   * <code>int64 createAt = 8;</code>
   */
  long getCreateAt();

  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>string signName = 9;</code>
   */
  String getSignName();
  /**
   * <pre>
   * 主题
   * </pre>
   *
   * <code>string signName = 9;</code>
   */
  com.google.protobuf.ByteString
      getSignNameBytes();
}
